# Generated by Django 5.0.6 on 2024-11-15 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_profile_location_skill"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"ordering": ["created"]},
        ),
    ]
